# MySQL setup

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_api?serverTimezone=UTC
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE







